### ISSUE TITLE
Incompatible module

### ISSUE THREAD

**Issue by cbaucom** [South-Paw/awesome-gatsby-starter#1]
Hello, I am trying to install this starter and am running into the following issue. Any idea how to resolve this? 

```
yarn install v0.16.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning styled-components > memoize-one@4.1.0: New custom equality api does not play well with all equality helpers. Please use v5.x
warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[2/4] 🚚  Fetching packages...
error lazy-universal-dotenv@2.0.0: The engine "yarn" is incompatible with this module. Expected version ">=1.0.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by South-Paw** [comment]
Sorry didn't mean to abandon your issue, I was unaware that there was one in here!

I haven't seen this personally but I'll see if I can reproduce it and get back to you.

**Comment by South-Paw** [comment]
Sorry didn't mean to abandon your issue, I was unaware that there was one on this repo. Anyhow I've tried to reproduce the issue and don't see it.

However your [yarn](https://yarnpkg.com/en/) version is `0.16.1` where-as the latest is `1.13.0`. Can you please update your yarn version and let me know if the issue persists?

**Comment by cbaucom** [comment]
You are correct. Updating my yarn version did the trick! Sorry about that.

**Comment by South-Paw** [comment]
No worries, glad it works 😄
