### ISSUE TITLE
failed during stage 'building site': Build script returned non-zero exit code: 1

### ISSUE THREAD

**Issue by alexanderfountain** [South-Paw/awesome-gatsby-starter#4]
Have not been able to get this to build on Netlify(Does work locally) 

I ran the docker image locally and got a more useful error:
ERR! Module not found: Error: Can't resolve '../../../public/static/d/1479812516.json' in '/opt/buildhome/repo/src/components/Navigation'
(node:3524) UnhandledPromiseRejectionWarning: ModuleNotFoundError: Module not found: Error: Can't resolve '../../../public/static/d/1479812516.json' in '/opt/buildhome/repo/src/components/Navigation'

It looks to have something to do with the staticquery.

**Comment by South-Paw** [comment]
Hi there,

When raising an issue, please provide as much information as possible such as your environment, changes to the code, etc etc - these things help maintainers to understand what's going wrong and provide help!

The repo is built by Netlify on commit/push/etc so I triggered another build to check it was still working and it [deployed correctly](https://app.netlify.com/sites/awesome-gatsby-starter/deploys/5de5abfdb9622101c43e8686).

At a glance, this issue does not look like it is to do with the starter library so if you could answer the following I might be able to tell you where to start with the isssue;

* what command are you running to build it?
* have you tried isolating/investigating the issue within the `src/components/Navigation`?
* are you building ONLY the starter's code (ie; clean slate) or have you made any changes/additions to the code?
* have you tried building a 'clean slate' of the starter to see if it works?

Let me know how you get on and I'll try help if I can 👍

**Comment by alexanderfountain** [comment]
Thank you for the quick response! 
I'm running macOS Mojave

I created a new gatsby projects per your instructions.:"gatsby new your-projects-name https://github.com/South-Paw/awesome-gatsby-starter"

I created a new github repo and pushed up the initial commit.

I created a new netlify site pointing to my new github repo.

My Netlify build command is: "yarn build:storybook"

My Netlify publish directory is: "public/docs"

In netlify this gives the error "failed during stage 'building site': Build script returned non-zero exit code: 1"

I started the netlify build image locally with Docker and got some more useful errors in both src/components/Navigation and src/components/Site

It looks to be something to do with the staticQuery. I commented out the staticQuery in the navigation component, and commented the calls to the seo component in the site component because the seo component also has staticqueries. This built and published successfully on Netlify.

Here is the link https://romantic-dubinsky-b4d0c3.netlify.com/?path=/story/components-navigation--simple

I replaced the static query result const with just a hard coded: "THE NAME"

**Comment by South-Paw** [comment]
I suspect that because you're not building Gatsby before building Storybook, the static queries in the components don't have any generated data to use.

Instead of only building Storybook, try `yarn build && yarn build:storybook` so that Gatsby has generated the static query data before Storybook tries to access it. This is also the Netlify build command that the preview site uses to build.

Let me know how you get on with that :)

**Comment by alexanderfountain** [comment]
Well that was it! My savior! Close this issue!

**Comment by South-Paw** [comment]
Good to hear!

I'll also add something in the readme about needing to build Gatsby before Storybook so static queries work 👍

Thanks for using the project!
