### ISSUE TITLE
--prefix-paths

### ISSUE THREAD

**Issue by bsamadi** [South-Paw/awesome-gatsby-starter#7]
It seems that the path prefix is ignored. I have these settings:

`     pathPrefix: '/Static-Website-Gatsby-South-Paw',`
`     basepath: 'https://elearninghub.github.io',`

The menus don't include the path prefix. You can see the website here:
https://elearninghub.github.io/Static-Website-Gatsby-South-Paw/

The source code is here: 
https://github.com/eLearningHub/Static-Website-Gatsby-South-Paw

**Comment by South-Paw** [comment]
Hey,

`pathPrefix` is not used by anything in the starter so naturally it won't do anything if you set it in the `siteMetadata`.

`basePath` should be set as the true base path of your site - in your case:

> `basepath: 'https://elearninghub.github.io/Static-Website-Gatsby-South-Paw/',`

Can I ask - what suggested you add the `pathPrefix` to the `siteMetadata`? Its not documented on this starter anywhere so I'm keen to know where you got it from

**Comment by bsamadi** [comment]
I am new to Gatsby and I had seen another starter using `pathPrefix`:  
https://github.com/eLearningHub/Static-Website-Gatsby-GitBook

I removed `pathPrefix` and used:

`basepath: 'https://elearninghub.github.io/Static-Website-Gatsby-South-Paw/',`

It seems that Gatsby ignores the `/Static-Website-Gatsby-South-Paw/` part. The menus are still not valid.

**Comment by bsamadi** [comment]
I had to switch from GitHub Pages to Netlify to avoid using `pathPrefix`.

**Comment by South-Paw** [comment]
The starter assumes it's being hosted on the root of the domain, if its not then its reasonably expected that you would make changes to the source to fix that. You don't "have" to switch from GitHub pages to Netlify to fix this issue, but it will solve it I guess.
